version: '3.8'

services:
  db:
    ports:
      - "5432:5432"

  rewind:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: builder
      args:
        version: "${VERSION:-0.0.1}"
    volumes:
      - rewind_build:/app/_build
      - rewind_deps:/app/deps
      - ./.env:/app/.env
      - ./mix.exs:/app/mix.exs
      - ./mix.lock:/app/mix.lock
      - ./config:/app/config
      - ./lib:/app/lib
      - ./priv/tai/order_repo:/app/priv/tai/order_repo
    entrypoint: "sh -c 'mix setup.deps && elixir --sname rewind -S mix phx.server'"

volumes:
  rewind_build:
  rewind_deps:
